"""M0H — ACM v0.20.0 Legacy Memory Contamination Cleanup promotion gates (D047)."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from aria_core import acm_bridge, memory_manager

# Genuine pre-D046 snapshot generated by standalone ACM v0.18.4 (commit
# 3023ed8): four legitimate user memories plus five artifacts the pre-D046
# encode boundary accepted (tool, diagnostic, reflection, system, infra).
FIXTURE = Path(__file__).resolve().parent / "fixtures" / "pre_d046_contaminated_snapshot.json"

ARTIFACT_PROBES = (
    "tool memory_search",
    "probe-yellow",
    "reflection trace",
    "session initialized",
    "memory backend timeout",
)


def _seed_assistant_aria() -> None:
    from aria_acm.acm.identity.assistant_profile import AssistantIdentityProfile

    eng = acm_bridge.get_engine()
    eng.identity.set_assistant_profile(
        AssistantIdentityProfile(name="ARIA", role="assistant")
    )


@pytest.fixture(autouse=True)
def _m0h_isolation(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setenv("ARIA_ACM_SHADOW", "0")
    monkeypatch.setenv("ARIA_ACM_PRIMARY", "1")
    monkeypatch.setenv("ARIA_ACM_ROLLBACK", "0")
    monkeypatch.setenv("ARIA_ACM_LEGACY_READ_FALLBACK", "0")
    monkeypatch.setenv("ARIA_ACM_PERSIST_PATH", str(tmp_path / "acm_m0h.db"))
    monkeypatch.setenv("ARIA_ACM_AUTO_PERSIST", "1")
    memory_manager.reset_for_tests()
    acm_bridge.reset_for_tests()
    yield
    memory_manager.reset_for_tests()
    acm_bridge.reset_for_tests()


def _speak(q: str) -> tuple[dict, str]:
    out = acm_bridge.primary_cognitive_speak(q)
    return out["result"], (out.get("speech") or "").strip()


def _engine_with_legacy_graph():
    """Engine over a contaminated pre-D046 graph, bypassing the upgrade hook."""
    engine = acm_bridge.get_engine()
    engine.import_snapshot(str(FIXTURE))
    return engine


def _store_blob(engine) -> str:
    return json.dumps(
        {
            "experiences": [e.summary for e in engine.store.experiences.values()],
            "metadata": [e.meta_dict() for e in engine.store.experiences.values()],
            "concepts": [c.to_public() for c in engine.store.concepts.values()],
            "provenance": [p.to_public() for p in engine.store.provenance.values()],
        },
        sort_keys=True,
    ).lower()


@pytest.mark.m0h
def test_m0h_01_embedded_version_pin() -> None:
    """M0H-01: embedded ACM matches standalone v0.20.0 pin."""
    from aria_acm.acm import __version__

    assert __version__ == "0.20.0"
    meta = json.loads(Path("aria_acm/VERSION.json").read_text(encoding="utf-8"))
    assert meta["source_version"] == "0.20.0"
    assert meta["source_tag"] == "v0.20.0"
    assert meta["source_commit"] == "b996fe8128c8104c4f1a7a0e633f8b28087a780d"
    assert meta["aria_acm_local_version"] == "aria-acm-v0.20.0-1"
    assert meta["promotion"] == "M0H"
    assert meta.get("promotion_decision") == "D047"
    for decision in (
        "D038",
        "D039",
        "D040",
        "D041",
        "D042",
        "D043",
        "D044",
        "D045",
        "D046",
        "D047",
    ):
        assert decision in meta.get("includes", [])


@pytest.mark.m0h
def test_m0h_02_d047_migration_vendored() -> None:
    """M0H-02: D047 cleanup module and engine entry point are vendored."""
    from aria_acm.acm.provenance import (
        classify_untrusted_artifact,
        cleanup_legacy_contamination,
    )

    assert classify_untrusted_artifact("Tool memory_search worked for: x") == "tool_output"
    assert classify_untrusted_artifact("My favorite color is blue.") is None
    engine = acm_bridge.get_engine()
    assert callable(engine.cleanup_legacy_contamination)
    assert callable(cleanup_legacy_contamination)


@pytest.mark.m0h
def test_m0h_03_contaminated_graph_recalls_artifact_before_cleanup() -> None:
    """M0H-03: expected pre-cleanup state — favorite color contaminated."""
    engine = _engine_with_legacy_graph()
    result = engine.cognitive_respond("What is my favorite color?")
    assert result["status"] == "known"
    assert "probe-yellow" in (result["memory"] or "")


@pytest.mark.m0h
def test_m0h_04_cleanup_removes_contamination_and_preserves_user_memory() -> None:
    """M0H-04: cleanup removes the five artifacts, preserves user memories."""
    engine = _engine_with_legacy_graph()
    report = engine.cleanup_legacy_contamination()

    assert report["removed_experiences"] == 5
    assert set(report["reasons"].values()) == {
        "legacy_untrusted_artifact:tool_output",
        "legacy_untrusted_artifact:diagnostic_output",
        "legacy_untrusted_artifact:reflection_output",
        "legacy_untrusted_artifact:system_message",
        "legacy_untrusted_artifact:infrastructure_log",
    }
    blob = _store_blob(engine)
    for probe in ARTIFACT_PROBES:
        assert probe not in blob
    summaries = " | ".join(e.summary.lower() for e in engine.store.experiences.values())
    assert "jeff" in summaries
    assert "blue" in summaries
    assert "sarah" in summaries
    assert "science museum" in summaries


@pytest.mark.m0h
def test_m0h_05_favorite_color_restored_to_blue() -> None:
    """M0H-05: the artifact-superseded preference is restored to blue."""
    engine = _engine_with_legacy_graph()
    engine.cleanup_legacy_contamination()
    _seed_assistant_aria()

    result, speech = _speak("What is my favorite color?")
    assert result["status"] == "known"
    assert "your favorite color is blue" in speech.lower()
    assert result["uncertainty"] is None
    values = {
        a.value: a.active
        for c in engine.store.concepts.values()
        for a in c.attributes
        if a.key == "favorite_color"
    }
    assert values == {"blue": True}


@pytest.mark.m0h
def test_m0h_06_identity_preserved() -> None:
    """M0H-06: user identity (Jeff) survives cleanup; assistant stays ARIA."""
    engine = _engine_with_legacy_graph()
    engine.cleanup_legacy_contamination()
    _seed_assistant_aria()

    names = sorted(
        (a.key, a.value, a.active)
        for c in engine.store.concepts.values()
        if c.identity
        for a in c.attributes
        if a.key == "name"
    )
    assert ("name", "Jeff", True) in names
    asst_result, asst_speech = _speak("Who are you?")
    assert asst_result["status"] == "known"
    assert "aria" in asst_speech.lower()
    assert "jeff" not in asst_speech.lower()


@pytest.mark.m0h
def test_m0h_07_cleanup_is_idempotent() -> None:
    """M0H-07: second run removes nothing and leaves the store checksum-equal."""
    engine = _engine_with_legacy_graph()
    first = engine.cleanup_legacy_contamination()
    assert first["removed_experiences"] == 5

    checksum = engine.verify_persistence()["checksum"]
    second = engine.cleanup_legacy_contamination()
    assert second["clean"] is True
    assert second["removed_experiences"] == 0
    assert second["removed_concepts"] == 0
    assert second["removed_attributes"] == 0
    assert second["removed_provenance"] == 0
    assert engine.verify_persistence()["checksum"] == checksum


@pytest.mark.m0h
def test_m0h_08_upgrade_path_runs_exactly_once(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """M0H-08: host upgrade path migrates an existing store once, then never again."""
    from aria_acm.acm.api.engine import CognitiveEngine

    # Build an existing contaminated durable store (as a pre-D046 install).
    persist = tmp_path / "existing" / "cognitive.db"
    seeder = CognitiveEngine(agent_id="aria", persist_path=str(persist), auto_persist=True)
    seeder.import_snapshot(str(FIXTURE))
    seeder.flush(kind="checkpoint")

    monkeypatch.setenv("ARIA_ACM_PERSIST_PATH", str(persist))
    acm_bridge.reset_for_tests()
    engine = acm_bridge.get_engine()

    marker = persist.with_name(persist.name + ".d047_cleanup.json")
    assert marker.is_file(), "upgrade path must record one-time migration"
    recorded = acm_bridge.legacy_cleanup_report()
    assert recorded is not None
    assert recorded["report"]["removed_experiences"] == 5
    blob = _store_blob(engine)
    for probe in ARTIFACT_PROBES:
        assert probe not in blob

    # Restart: already-migrated store is not processed again.
    marker_bytes = marker.read_bytes()
    acm_bridge.reset_for_tests()
    engine2 = acm_bridge.get_engine()
    assert marker.read_bytes() == marker_bytes
    result = engine2.cognitive_respond("What is my favorite color?")
    assert result["memory"] == "Your favorite color is blue."


@pytest.mark.m0h
def test_m0h_09_upgrade_path_no_op_on_clean_store(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """M0H-09: clean graphs are never altered by the upgrade path."""
    persist = tmp_path / "clean" / "cognitive.db"
    monkeypatch.setenv("ARIA_ACM_PERSIST_PATH", str(persist))
    acm_bridge.reset_for_tests()
    _seed_assistant_aria()
    acm_bridge.primary_remember("My favorite color is blue.", entry_type="preference")
    checksum = acm_bridge.get_engine().verify_persistence()["checksum"]

    recorded = acm_bridge.legacy_cleanup_report()
    assert recorded is not None
    assert recorded["report"]["clean"] is True
    assert recorded["report"]["removed_experiences"] == 0
    assert acm_bridge.get_engine().verify_persistence()["checksum"] == checksum


@pytest.mark.m0h
def test_m0h_10_d046_gate_unchanged_after_cleanup() -> None:
    """M0H-10: D046 still rejects untrusted and unknown sources post-cleanup."""
    from aria_acm.acm.provenance import (
        HostOperation,
        IngestionActor,
        IngestionProvenance,
        MessageRole,
    )

    engine = _engine_with_legacy_graph()
    engine.cleanup_legacy_contamination()

    cases = (
        (IngestionActor.TOOL, HostOperation.TOOL_EXECUTION, MessageRole.TOOL_RESULT),
        (IngestionActor.DIAGNOSTIC, HostOperation.DIAGNOSTIC, MessageRole.DIAGNOSTIC_OUTPUT),
        (IngestionActor.REFLECTION, HostOperation.REFLECTION, MessageRole.REFLECTION_OUTPUT),
        (IngestionActor.SYSTEM, HostOperation.SYSTEM_EVENT, MessageRole.SYSTEM_MESSAGE),
        (
            IngestionActor.INFRASTRUCTURE,
            HostOperation.SYSTEM_EVENT,
            MessageRole.INFRASTRUCTURE_LOG,
        ),
        (IngestionActor.UNKNOWN, HostOperation.UNKNOWN, MessageRole.UNKNOWN),
    )
    before = len(engine.store.experiences)
    for actor, operation, role in cases:
        rejected = engine.encode(
            "Artifact: my favorite color is artifact-mauve.",
            provenance=IngestionProvenance(
                actor=actor, host_operation=operation, message_role=role
            ),
        )
        assert rejected["encoded"] is False
        assert rejected["reason"] == "memory_trust"
    assert engine.encode("My favorite color is artifact-mauve.")["detail"] == (
        "missing_provenance"
    )
    assert len(engine.store.experiences) == before
    result = engine.cognitive_respond("What is my favorite color?")
    assert "artifact-mauve" not in (result["memory"] or "")


@pytest.mark.m0h
def test_m0h_11_no_new_contamination_and_cleanup_stays_clean() -> None:
    """M0H-11: repeated injection cannot recreate contamination post-migration."""
    from aria_acm.acm.provenance import (
        HostOperation,
        IngestionActor,
        IngestionProvenance,
        MessageRole,
    )

    engine = _engine_with_legacy_graph()
    engine.cleanup_legacy_contamination()
    tool = IngestionProvenance(
        actor=IngestionActor.TOOL,
        host_operation=HostOperation.MEMORY_SEARCH,
        message_role=MessageRole.TOOL_RESULT,
    )
    for _ in range(10):
        assert (
            engine.encode(
                "Tool memory_search worked for: Show the evidence for my favorite color.",
                provenance=tool,
            )["encoded"]
            is False
        )
    result = engine.cognitive_respond("What is my favorite color?")
    assert result["memory"] == "Your favorite color is blue."
    assert engine.cleanup_legacy_contamination()["clean"] is True


@pytest.mark.m0h
def test_m0h_12_host_teach_and_recall_regression() -> None:
    """M0H-12: Identity + Preference certifications hold through the host path."""
    _seed_assistant_aria()
    acm_bridge.primary_remember("My name is Jeff.", entry_type="fact", tags=["identity"])
    acm_bridge.primary_remember("My favorite color is blue.", entry_type="preference")

    user_result, user_speech = _speak("Who am I?")
    assert user_result["status"] == "known"
    assert "your name is jeff" in user_speech.lower()
    color_result, color_speech = _speak("What is my favorite color?")
    assert color_result["status"] == "known"
    assert "your favorite color is blue" in color_speech.lower()
    assert color_result["uncertainty"] is None
