#!/usr/bin/env bash
# Install workstation, aria, and aiplatform into ~/.local/bin (works from any directory).
set -euo pipefail

JARVIS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PLATFORM_ROOT="${AI_PLATFORM_ROOT:-$(dirname "$JARVIS_ROOT")/AI-Platform}"
AI_ROOT="${AI_ROOT:-$(dirname "$PLATFORM_ROOT")}"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ai-workstation"
BIN_DIR="${HOME}/.local/bin"

mkdir -p "$CONFIG_DIR" "$BIN_DIR"

cat >"$CONFIG_DIR/paths.env" <<EOF
# AI Workstation paths — generated by install-global-commands.sh
JARVIS_ROOT=$JARVIS_ROOT
AI_PLATFORM_ROOT=$PLATFORM_ROOT
AI_ROOT=$AI_ROOT
EOF

write_wrapper() {
  local name="$1"
  local body="$2"
  local target="$BIN_DIR/$name"
  cat >"$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail
CONFIG="\${XDG_CONFIG_HOME:-\$HOME/.config}/ai-workstation/paths.env"
if [[ -f "\$CONFIG" ]]; then
  # shellcheck disable=SC1090
  source "\$CONFIG"
fi
${body}
EOF
  chmod +x "$target"
}

write_wrapper workstation 'exec "${JARVIS_ROOT:?Set JARVIS_ROOT or run install-global-commands.sh}/workstation" "$@"'

write_wrapper aiplatform 'PY="${JARVIS_ROOT}/venv/bin/python"
[[ -x "$PY" ]] || PY=python3
exec "$PY" -m aiplatform.cli "$@"'

write_wrapper aria 'PY="${JARVIS_ROOT}/venv/bin/python"
[[ -x "$PY" ]] || PY=python3
case "${1:-}" in
  ""|--chat|chat)
    exec bash "${JARVIS_ROOT}/scripts/launch-jarvis.sh"
    ;;
  --tray|tray)
    exec "$PY" "${JARVIS_ROOT}/main.py" tray
    ;;
  --serve|serve)
    exec "$PY" "${JARVIS_ROOT}/main.py" serve
    ;;
  --status|status)
    exec "${JARVIS_ROOT}/workstation" status
    ;;
  --help|-h|help)
    echo "Usage: aria [--chat|--tray|--serve|--status]"
    echo "  aria          Open Aria (default)"
    echo "  aria --tray   Tray + background server"
    echo "  aria --serve  Headless API server"
    echo "  aria --status Workstation status JSON"
    exit 0
    ;;
  *)
    exec "$PY" "${JARVIS_ROOT}/main.py" "$@"
    ;;
esac'

echo "Installed global commands:"
echo "  $BIN_DIR/workstation"
echo "  $BIN_DIR/aria"
echo "  $BIN_DIR/aiplatform"
echo "Config: $CONFIG_DIR/paths.env"

case ":${PATH}:" in
  *":${BIN_DIR}:"*) ;;
  *)
    echo ""
    echo "Add ~/.local/bin to PATH if needed:"
    echo '  export PATH="$HOME/.local/bin:$PATH"'
    ;;
esac
