"""Aria Core Capability Registry (Phase 3).

Describes every Capability Bus verb. Implementations stay under jarvis/aiplatform.
"""

from __future__ import annotations

from typing import Any

CAPABILITY_VERSION = "2.0-phase3"

# Registry fields required by Phase 3 mission.
_REQUIRED_FIELDS = (
    "id",
    "purpose",
    "owner",
    "provider",
    "current_implementation",
    "consumers",
    "dependencies",
    "health",
    "version",
    "public_api",
    "permission_requirements",
    "learning_effects",
    "memory_effects",
    "recovery_behavior",
)

REGISTRY: dict[str, dict[str, Any]] = {
    "remember": {
        "id": "remember",
        "purpose": "Persist an item into Aria memory",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.remember",
        "current_implementation": "jarvis.modules.memory.MemoryStore.add",
        "consumers": ["applications", "reasoning", "interfaces"],
        "dependencies": ["aria_core.memory", "aria_core.learning"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["remember"],
        "permission_requirements": ["memory.write"],
        "learning_effects": "May pass through Learning Governor on commit paths",
        "memory_effects": "Creates or updates durable memory entries",
        "recovery_behavior": "Fail soft; existing store remains authoritative",
        "contract_id": "remember",
        "future_implementation_owner": "aria_core.memory",
    },
    "recall": {
        "id": "recall",
        "purpose": "Retrieve memory entries by query or id",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.recall",
        "current_implementation": "jarvis.modules.memory.MemoryStore.search/get",
        "consumers": ["applications", "reasoning", "interfaces"],
        "dependencies": ["aria_core.memory"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["recall"],
        "permission_requirements": ["memory.read"],
        "learning_effects": "none",
        "memory_effects": "Read-only",
        "recovery_behavior": "Return empty hits on store unavailability",
        "contract_id": "recall",
        "future_implementation_owner": "aria_core.memory",
    },
    "learn": {
        "id": "learn",
        "purpose": "Propose and commit learning updates via Learning Governor",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.learn",
        "current_implementation": "jarvis.learning_governor.propose/commit",
        "consumers": ["memory", "nlu", "applications"],
        "dependencies": ["aria_core.learning"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["learn"],
        "permission_requirements": ["learning.write"],
        "learning_effects": "Creates proposals; commit applies existing writers",
        "memory_effects": "Indirect when apply writes memory",
        "recovery_behavior": "Passthrough governor; no silent discard in Phase 3",
        "contract_id": "learn",
        "future_implementation_owner": "aria_core.learning",
    },
    "reason": {
        "id": "reason",
        "purpose": "Conversational reasoning / assistant process",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.reason",
        "current_implementation": "jarvis.assistant / jarvis.assistant_instance",
        "consumers": ["interfaces", "applications"],
        "dependencies": ["aria_core.reasoning", "aria_core.identity"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["reason"],
        "permission_requirements": ["chat"],
        "learning_effects": "May record corrections through existing NLU paths",
        "memory_effects": "May read/write via existing assistant flows",
        "recovery_behavior": "Surface existing assistant errors unchanged",
        "contract_id": "reason",
        "future_implementation_owner": "aria_core.reasoning",
    },
    "plan": {
        "id": "plan",
        "purpose": "Multi-agent / planner coordination surface",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.plan",
        "current_implementation": "jarvis.agents.coordinator",
        "consumers": ["applications", "capabilities"],
        "dependencies": ["aria_core.planning"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["plan"],
        "permission_requirements": ["planning"],
        "learning_effects": "none direct",
        "memory_effects": "Planner store may persist plans",
        "recovery_behavior": "Report unavailable if coordinator missing",
        "contract_id": "plan",
        "future_implementation_owner": "aria_core.planning",
    },
    "reference": {
        "id": "reference",
        "purpose": "Local-first reference / documentation search",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.reference",
        "current_implementation": "jarvis.reference_engine.search_reference",
        "consumers": ["reasoning", "interfaces", "operations"],
        "dependencies": ["aria_core.reference"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["reference"],
        "permission_requirements": ["reference.read"],
        "learning_effects": "none",
        "memory_effects": "none",
        "recovery_behavior": "Return structured empty/error payload",
        "contract_id": "reference",
        "future_implementation_owner": "aria_core.reference",
    },
    "search": {
        "id": "search",
        "purpose": "Knowledge / RAG search",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.search",
        "current_implementation": "jarvis.knowledge.search",
        "consumers": ["applications", "reasoning", "reference"],
        "dependencies": ["aria_core.knowledge"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["search"],
        "permission_requirements": ["knowledge.read"],
        "learning_effects": "none",
        "memory_effects": "none",
        "recovery_behavior": "Return empty hits on failure",
        "contract_id": "search",
        "future_implementation_owner": "aria_core.knowledge",
    },
    "infer": {
        "id": "infer",
        "purpose": "LLM inference routing surface",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.infer",
        "current_implementation": "jarvis.llm / jarvis.inference",
        "consumers": ["reasoning", "applications"],
        "dependencies": ["aria_core.reasoning", "aria_core.runtime"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["infer"],
        "permission_requirements": ["inference"],
        "learning_effects": "none direct",
        "memory_effects": "none direct",
        "recovery_behavior": "Propagate existing LLM client errors",
        "contract_id": "infer",
        "future_implementation_owner": "aria_core.reasoning",
    },
    "execute_tool": {
        "id": "execute_tool",
        "purpose": "Dispatch a registered handler / tool action",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.execute_tool",
        "current_implementation": "jarvis.handlers.registry.call_action",
        "consumers": ["reasoning", "applications"],
        "dependencies": ["jarvis.handlers.registry", "jarvis.modules.capability_adapter"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["execute_tool", "list_tools"],
        "permission_requirements": ["tools.execute"],
        "learning_effects": "none direct",
        "memory_effects": "Tool-dependent",
        "recovery_behavior": "Raise KeyError for unknown actions (existing behavior)",
        "contract_id": "execute_tool",
        "future_implementation_owner": "aria_core.capabilities",
    },
    "schedule": {
        "id": "schedule",
        "purpose": "Background / job scheduling surface",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.schedule",
        "current_implementation": "jarvis.runtime_introspection jobs + handler queues",
        "consumers": ["applications", "operations"],
        "dependencies": ["aria_core.runtime", "jarvis.handlers.registry"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["schedule", "list_jobs"],
        "permission_requirements": ["jobs.schedule"],
        "learning_effects": "none",
        "memory_effects": "none",
        "recovery_behavior": "Report status; do not invent a new scheduler",
        "contract_id": "schedule",
        "future_implementation_owner": "aria_core.runtime",
    },
    "observe": {
        "id": "observe",
        "purpose": "Operational observation / overview snapshot",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.observe",
        "current_implementation": "aiplatform.mission_control.aggregator.collect_overview",
        "consumers": ["operations", "interfaces"],
        "dependencies": ["aria_core.operations"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["observe"],
        "permission_requirements": ["ops.read"],
        "learning_effects": "none",
        "memory_effects": "none",
        "recovery_behavior": "Return structured unavailable payload",
        "contract_id": "observe",
        "future_implementation_owner": "aria_core.operations",
    },
    "notify": {
        "id": "notify",
        "purpose": "Operator / system notification",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.notify",
        "current_implementation": "aiplatform.mission_control.notifications.notify",
        "consumers": ["operations", "interfaces"],
        "dependencies": ["aiplatform.mission_control.notifications"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["notify"],
        "permission_requirements": ["ops.notify"],
        "learning_effects": "none",
        "memory_effects": "none",
        "recovery_behavior": "No-op soft fail when platform absent",
        "contract_id": "notify",
        "future_implementation_owner": "aria_core.operations",
    },
    "diagnose": {
        "id": "diagnose",
        "purpose": "Workstation / platform diagnosis",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.diagnose",
        "current_implementation": "aiplatform.workstation.operations.diagnose",
        "consumers": ["operations", "applications"],
        "dependencies": ["aiplatform.workstation.operations"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["diagnose"],
        "permission_requirements": ["ops.diagnose"],
        "learning_effects": "none",
        "memory_effects": "none",
        "recovery_behavior": "Return issues list; never mutate",
        "contract_id": "diagnose",
        "future_implementation_owner": "aria_core.platform",
    },
    "repair": {
        "id": "repair",
        "purpose": "Safe repair entrypoint",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.repair",
        "current_implementation": "aiplatform.workstation.operations.recover_safe / repair modules",
        "consumers": ["operations"],
        "dependencies": ["aiplatform.workstation.operations", "aiplatform.workstation.repair"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["repair"],
        "permission_requirements": ["ops.repair"],
        "learning_effects": "none",
        "memory_effects": "none",
        "recovery_behavior": "Delegates to existing safe recovery only",
        "contract_id": "repair",
        "future_implementation_owner": "aria_core.platform",
    },
    "backup": {
        "id": "backup",
        "purpose": "Data backup surface pointer",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.backup",
        "current_implementation": "jarvis scripts/backup-data.sh + MC recovery panel",
        "consumers": ["operations", "interfaces"],
        "dependencies": ["aria_core.operations"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["backup", "latest_backup_hint"],
        "permission_requirements": ["ops.backup"],
        "learning_effects": "none",
        "memory_effects": "Creates archives; does not alter live memory",
        "recovery_behavior": "Report script/path availability; do not invent backup logic",
        "contract_id": "backup",
        "future_implementation_owner": "aria_core.operations",
    },
    "recover": {
        "id": "recover",
        "purpose": "Safe recovery / restore surface",
        "owner": "aria_core.capabilities",
        "provider": "aria_core.capability_bus.recover",
        "current_implementation": "aiplatform.workstation.operations.recover_safe",
        "consumers": ["operations"],
        "dependencies": ["aiplatform.workstation.operations"],
        "health": "probe",
        "version": CAPABILITY_VERSION,
        "public_api": ["recover"],
        "permission_requirements": ["ops.recover"],
        "learning_effects": "none",
        "memory_effects": "May restart services; memory stores untouched by bus",
        "recovery_behavior": "Delegates to recover_safe unchanged",
        "contract_id": "recover",
        "future_implementation_owner": "aria_core.platform",
    },
}


def required_fields() -> tuple[str, ...]:
    return _REQUIRED_FIELDS


def all_capability_ids() -> list[str]:
    return sorted(REGISTRY.keys())


def get_capability(capability_id: str) -> dict[str, Any] | None:
    rec = REGISTRY.get(capability_id)
    return dict(rec) if rec else None


def list_capabilities() -> list[dict[str, Any]]:
    return [dict(REGISTRY[k]) for k in sorted(REGISTRY)]


def validate_registry() -> list[str]:
    """Return list of validation errors (empty = ok)."""
    errors: list[str] = []
    for cid, rec in REGISTRY.items():
        for field in _REQUIRED_FIELDS:
            if field not in rec:
                errors.append(f"{cid}: missing field {field}")
        if rec.get("id") != cid:
            errors.append(f"{cid}: id mismatch")
    return errors


def dependency_graph() -> dict[str, list[str]]:
    """Capability id → dependency strings (for MC visualization)."""
    return {cid: list(rec.get("dependencies") or []) for cid, rec in sorted(REGISTRY.items())}
