"""Aria Core Event Contracts (Phase 4)."""

from __future__ import annotations

from typing import Any

from aria_core.event_types import ALL_EVENT_TYPES, EVENT_VERSION

# Purpose, publisher, subscribers, payload, ordering, reliability, replay, version
CONTRACTS: dict[str, dict[str, Any]] = {
    "MemoryCreated": {
        "purpose": "A memory entry was created",
        "publisher": "aria_core.capability_bus.remember / learning paths",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"entry_id": "str?", "namespace": "str?", "entry_type": "str?"},
        "ordering": "per-publisher FIFO; no global total order",
        "reliability": "best-effort in-process; publish never fails caller",
        "replay_support": "ring buffer only (no durable replay log in Phase 4)",
        "version": EVENT_VERSION,
    },
    "MemoryUpdated": {
        "purpose": "A memory entry was updated",
        "publisher": "aria_core.event_bus (helper); future memory writers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"entry_id": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "MemoryDeleted": {
        "purpose": "A memory entry was deleted",
        "publisher": "aria_core.event_bus (helper); future memory writers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"entry_id": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "KnowledgeAdded": {
        "purpose": "Knowledge document/source added",
        "publisher": "aria_core.event_bus (helper); knowledge writers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"doc_id": "str?", "source": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "KnowledgeUpdated": {
        "purpose": "Knowledge document/source updated",
        "publisher": "aria_core.event_bus (helper)",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"doc_id": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "LearningProposed": {
        "purpose": "Learning Governor created a proposal",
        "publisher": "jarvis.learning_governor.propose",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"kind": "str", "proposal_source": "str", "payload_keys": "list[str]"},
        "ordering": "FIFO with LearningAccepted for same proposal",
        "reliability": "best-effort; never blocks propose()",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "LearningAccepted": {
        "purpose": "Learning Governor committed a proposal",
        "publisher": "jarvis.learning_governor.commit",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"kind": "str", "proposal_source": "str", "ok": "bool"},
        "ordering": "after LearningProposed for same flow",
        "reliability": "best-effort; never blocks commit()",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "LearningRejected": {
        "purpose": "Learning commit apply() raised",
        "publisher": "jarvis.learning_governor.commit",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"kind": "str", "proposal_source": "str", "error": "str"},
        "ordering": "replaces LearningAccepted for failed apply",
        "reliability": "best-effort; exception still propagates",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ReferenceLookup": {
        "purpose": "Reference search performed",
        "publisher": "aria_core.capability_bus.reference",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"query": "str", "subject": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ReferenceIndexed": {
        "purpose": "Reference corpus indexed",
        "publisher": "aria_core.event_bus (helper); reference indexers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"source": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ReasoningStarted": {
        "purpose": "Assistant reasoning began",
        "publisher": "aria_core.capability_bus.reason",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"message_len": "int"},
        "ordering": "paired with ReasoningFinished",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ReasoningFinished": {
        "purpose": "Assistant reasoning finished",
        "publisher": "aria_core.capability_bus.reason",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool", "error": "str?"},
        "ordering": "after ReasoningStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "PlanStarted": {
        "purpose": "Planning surface invoked",
        "publisher": "aria_core.capability_bus.plan",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"action": "str"},
        "ordering": "paired with PlanCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "PlanCompleted": {
        "purpose": "Planning surface returned",
        "publisher": "aria_core.capability_bus.plan",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"action": "str", "ok": "bool"},
        "ordering": "after PlanStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "InferenceStarted": {
        "purpose": "LLM inference began",
        "publisher": "aria_core.capability_bus.infer",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"prompt_len": "int"},
        "ordering": "paired with InferenceFinished",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "InferenceFinished": {
        "purpose": "LLM inference finished",
        "publisher": "aria_core.capability_bus.infer",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool", "error": "str?"},
        "ordering": "after InferenceStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ToolStarted": {
        "purpose": "Handler/tool dispatch began",
        "publisher": "aria_core.capability_bus.execute_tool",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"action": "str"},
        "ordering": "paired with ToolCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ToolCompleted": {
        "purpose": "Handler/tool dispatch finished",
        "publisher": "aria_core.capability_bus.execute_tool",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"action": "str", "ok": "bool", "error": "str?"},
        "ordering": "after ToolStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ApplicationStarted": {
        "purpose": "Application launch requested/completed",
        "publisher": "mission_control aggregator / event helpers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"app_id": "str"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ApplicationStopped": {
        "purpose": "Application stop requested/completed",
        "publisher": "mission_control aggregator / event helpers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"app_id": "str"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RuntimeConnected": {
        "purpose": "Runtime client connected",
        "publisher": "aria_core.event_bus (helper); runtime",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"mode": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RuntimeDisconnected": {
        "purpose": "Runtime client disconnected",
        "publisher": "aria_core.event_bus (helper); runtime",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"mode": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RepairStarted": {
        "purpose": "Repair/recover_safe began",
        "publisher": "aria_core.capability_bus.repair",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"mode": "str?"},
        "ordering": "paired with RepairCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RepairCompleted": {
        "purpose": "Repair/recover_safe finished",
        "publisher": "aria_core.capability_bus.repair",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool"},
        "ordering": "after RepairStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "BackupStarted": {
        "purpose": "Backup operation began",
        "publisher": "aria_core.event_bus (helper); backup runners",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"op": "str?"},
        "ordering": "paired with BackupCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "BackupCompleted": {
        "purpose": "Backup operation finished",
        "publisher": "aria_core.event_bus (helper); backup runners",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool"},
        "ordering": "after BackupStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RecoveryStarted": {
        "purpose": "Recovery began",
        "publisher": "aria_core.capability_bus.recover",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {},
        "ordering": "paired with RecoveryCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RecoveryCompleted": {
        "purpose": "Recovery finished",
        "publisher": "aria_core.capability_bus.recover",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool"},
        "ordering": "after RecoveryStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "StartupPhaseChanged": {
        "purpose": "Startup pipeline phase changed",
        "publisher": "mission_control / startup bridge",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"phase": "str"},
        "ordering": "startup sequence order",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ShutdownStarted": {
        "purpose": "Shutdown began",
        "publisher": "mission_control / runtime bridge",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {},
        "ordering": "paired with ShutdownCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ShutdownCompleted": {
        "purpose": "Shutdown finished",
        "publisher": "mission_control / runtime bridge",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {},
        "ordering": "after ShutdownStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
}


_REQUIRED = (
    "purpose",
    "publisher",
    "subscribers",
    "payload",
    "ordering",
    "reliability",
    "replay_support",
    "version",
)


def get_contract(event_type: str) -> dict[str, Any] | None:
    rec = CONTRACTS.get(event_type)
    return dict(rec) if rec else None


def list_contracts() -> list[dict[str, Any]]:
    return [dict(CONTRACTS[k]) for k in sorted(CONTRACTS)]


def validate_contracts() -> list[str]:
    errors: list[str] = []
    for name in ALL_EVENT_TYPES:
        if name not in CONTRACTS:
            errors.append(f"missing contract: {name}")
    for name, rec in CONTRACTS.items():
        if name not in ALL_EVENT_TYPES:
            errors.append(f"orphan contract: {name}")
        for field in _REQUIRED:
            if field not in rec:
                errors.append(f"{name}: missing {field}")
    return errors
