"""Aria Core Event Contracts (Phase 4)."""

from __future__ import annotations

from typing import Any

from aria_core.event_types import ALL_EVENT_TYPES, EVENT_VERSION

# Purpose, publisher, subscribers, payload, ordering, reliability, replay, version
CONTRACTS: dict[str, dict[str, Any]] = {
    "MemoryCreated": {
        "purpose": "A memory entry was created",
        "publisher": "aria_core.memory_manager.remember",
        "subscribers": ["timeline", "mission_control.events", "mission_control.memory"],
        "payload": {"entry_id": "str?", "namespace": "str?", "entry_type": "str?"},
        "ordering": "per-publisher FIFO; no global total order",
        "reliability": "best-effort in-process; publish never fails caller",
        "replay_support": "memory history + event ring (no content)",
        "version": EVENT_VERSION,
    },
    "MemoryUpdated": {
        "purpose": "A memory entry was updated",
        "publisher": "aria_core.memory_manager.update_memory",
        "subscribers": ["timeline", "mission_control.events", "mission_control.memory"],
        "payload": {"entry_id": "str?", "ok": "bool"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "memory history + event ring",
        "version": EVENT_VERSION,
    },
    "MemoryDeleted": {
        "purpose": "A memory entry was deleted",
        "publisher": "aria_core.memory_manager.forget",
        "subscribers": ["timeline", "mission_control.events", "mission_control.memory"],
        "payload": {"entry_id": "str?", "ok": "bool"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "memory history + event ring",
        "version": EVENT_VERSION,
    },
    "MemoryRead": {
        "purpose": "Memory read/get performed",
        "publisher": "aria_core.memory_manager",
        "subscribers": ["timeline", "mission_control.memory"],
        "payload": {"hit_count": "int", "mode": "str", "entry_id": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort; no contents in payload",
        "replay_support": "memory history",
        "version": EVENT_VERSION,
    },
    "MemoryWritten": {
        "purpose": "Memory write completed",
        "publisher": "aria_core.memory_manager.remember",
        "subscribers": ["timeline", "mission_control.memory"],
        "payload": {"entry_id": "str?", "entry_type": "str?", "namespace": "str?"},
        "ordering": "with MemoryCreated / MemoryCommit",
        "reliability": "best-effort in-process",
        "replay_support": "memory history",
        "version": EVENT_VERSION,
    },
    "MemoryMerged": {
        "purpose": "Two memory entries merged via update+delete",
        "publisher": "aria_core.memory_manager.merge_memories",
        "subscribers": ["timeline", "mission_control.memory"],
        "payload": {"keep_id": "str", "drop_id": "str", "ok": "bool"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "memory history",
        "version": EVENT_VERSION,
    },
    "MemorySearch": {
        "purpose": "Memory search performed",
        "publisher": "aria_core.memory_manager.search_memory",
        "subscribers": ["timeline", "mission_control.memory"],
        "payload": {"query_len": "int", "hit_count": "int", "duration_ms": "float"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort; no query text/contents in payload",
        "replay_support": "memory history",
        "version": EVENT_VERSION,
    },
    "MemoryCommit": {
        "purpose": "Memory proposal/write committed",
        "publisher": "aria_core.memory_manager",
        "subscribers": ["timeline", "mission_control.memory"],
        "payload": {"entry_id": "str?", "ok": "bool", "duration_ms": "float?"},
        "ordering": "after write",
        "reliability": "best-effort in-process",
        "replay_support": "memory history",
        "version": EVENT_VERSION,
    },
    "MemoryRollback": {
        "purpose": "Memory rollback requested (delete or history mark)",
        "publisher": "aria_core.memory_manager.rollback_memory",
        "subscribers": ["timeline", "mission_control.memory"],
        "payload": {"entry_id": "str?", "proposal_id": "str?", "ok": "bool", "mode": "str"},
        "ordering": "operator-triggered",
        "reliability": "best-effort; no invented restore storage",
        "replay_support": "memory history",
        "version": EVENT_VERSION,
    },
    "KnowledgeAdded": {
        "purpose": "Knowledge document/source added",
        "publisher": "aria_core.event_bus (helper); knowledge writers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"doc_id": "str?", "source": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "KnowledgeUpdated": {
        "purpose": "Knowledge document/source updated",
        "publisher": "aria_core.event_bus (helper)",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"doc_id": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "LearningProposed": {
        "purpose": "Learning Governor created a proposal",
        "publisher": "aria_core.learning_manager.propose",
        "subscribers": ["timeline", "mission_control.events", "mission_control.learning"],
        "payload": {
            "kind": "str",
            "proposal_source": "str",
            "proposal_id": "str",
            "origin": "str",
            "capability": "str",
            "payload_keys": "list[str]",
        },
        "ordering": "FIFO with LearningAccepted/Committed for same proposal",
        "reliability": "best-effort; never blocks propose()",
        "replay_support": "ring buffer + learning history",
        "version": EVENT_VERSION,
    },
    "LearningAccepted": {
        "purpose": "Learning proposal apply() succeeded",
        "publisher": "aria_core.learning_manager.commit",
        "subscribers": ["timeline", "mission_control.events", "mission_control.learning"],
        "payload": {"kind": "str", "proposal_source": "str", "ok": "bool", "proposal_id": "str"},
        "ordering": "after LearningProposed; paired with LearningCommitted",
        "reliability": "best-effort; never blocks commit()",
        "replay_support": "ring buffer + learning history",
        "version": EVENT_VERSION,
    },
    "LearningRejected": {
        "purpose": "Learning apply() raised or explicit reject_learning",
        "publisher": "aria_core.learning_manager",
        "subscribers": ["timeline", "mission_control.events", "mission_control.learning"],
        "payload": {"kind": "str", "proposal_source": "str", "error": "str", "proposal_id": "str"},
        "ordering": "replaces LearningAccepted for failed apply",
        "reliability": "best-effort; exception still propagates on apply failure",
        "replay_support": "ring buffer + learning history",
        "version": EVENT_VERSION,
    },
    "LearningCommitted": {
        "purpose": "Learning write committed via apply()",
        "publisher": "aria_core.learning_manager.commit",
        "subscribers": ["timeline", "mission_control.events", "mission_control.learning"],
        "payload": {"kind": "str", "proposal_id": "str", "ok": "bool", "duration_ms": "float"},
        "ordering": "immediately after LearningAccepted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer + learning history",
        "version": EVENT_VERSION,
    },
    "LearningReplayed": {
        "purpose": "History record re-surfaced for operators",
        "publisher": "aria_core.learning_manager.replay_learning",
        "subscribers": ["timeline", "mission_control.events", "mission_control.learning"],
        "payload": {"proposal_id": "str", "kind": "str?", "decision": "str?"},
        "ordering": "operator-triggered",
        "reliability": "best-effort; does not rewrite organs",
        "replay_support": "history lookup",
        "version": EVENT_VERSION,
    },
    "LearningRolledBack": {
        "purpose": "History marked rolled back (no Memory/Knowledge undo in Phase 5)",
        "publisher": "aria_core.learning_manager.rollback_learning",
        "subscribers": ["timeline", "mission_control.events", "mission_control.learning"],
        "payload": {"proposal_id": "str", "kind": "str?", "reason": "str?"},
        "ordering": "operator-triggered",
        "reliability": "best-effort; history-only",
        "replay_support": "history lookup",
        "version": EVENT_VERSION,
    },
    "ReferenceLookup": {
        "purpose": "Reference search performed",
        "publisher": "aria_core.capability_bus.reference",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"query": "str", "subject": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ReferenceIndexed": {
        "purpose": "Reference corpus indexed",
        "publisher": "aria_core.event_bus (helper); reference indexers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"source": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ReasoningStarted": {
        "purpose": "Assistant reasoning began",
        "publisher": "aria_core.capability_bus.reason",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"message_len": "int"},
        "ordering": "paired with ReasoningFinished",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ReasoningFinished": {
        "purpose": "Assistant reasoning finished",
        "publisher": "aria_core.capability_bus.reason",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool", "error": "str?"},
        "ordering": "after ReasoningStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "PlanStarted": {
        "purpose": "Planning surface invoked",
        "publisher": "aria_core.capability_bus.plan",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"action": "str"},
        "ordering": "paired with PlanCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "PlanCompleted": {
        "purpose": "Planning surface returned",
        "publisher": "aria_core.capability_bus.plan",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"action": "str", "ok": "bool"},
        "ordering": "after PlanStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "InferenceStarted": {
        "purpose": "LLM inference began",
        "publisher": "aria_core.capability_bus.infer",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"prompt_len": "int"},
        "ordering": "paired with InferenceFinished",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "InferenceFinished": {
        "purpose": "LLM inference finished",
        "publisher": "aria_core.capability_bus.infer",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool", "error": "str?"},
        "ordering": "after InferenceStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ToolStarted": {
        "purpose": "Handler/tool dispatch began",
        "publisher": "aria_core.capability_bus.execute_tool",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"action": "str"},
        "ordering": "paired with ToolCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ToolCompleted": {
        "purpose": "Handler/tool dispatch finished",
        "publisher": "aria_core.capability_bus.execute_tool",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"action": "str", "ok": "bool", "error": "str?"},
        "ordering": "after ToolStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ApplicationStarted": {
        "purpose": "Application launch requested/completed",
        "publisher": "mission_control aggregator / event helpers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"app_id": "str"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ApplicationStopped": {
        "purpose": "Application stop requested/completed",
        "publisher": "mission_control aggregator / event helpers",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"app_id": "str"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RuntimeConnected": {
        "purpose": "Runtime client connected",
        "publisher": "aria_core.event_bus (helper); runtime",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"mode": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RuntimeDisconnected": {
        "purpose": "Runtime client disconnected",
        "publisher": "aria_core.event_bus (helper); runtime",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"mode": "str?"},
        "ordering": "per-publisher FIFO",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RepairStarted": {
        "purpose": "Repair/recover_safe began",
        "publisher": "aria_core.capability_bus.repair",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"mode": "str?"},
        "ordering": "paired with RepairCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RepairCompleted": {
        "purpose": "Repair/recover_safe finished",
        "publisher": "aria_core.capability_bus.repair",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool"},
        "ordering": "after RepairStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "BackupStarted": {
        "purpose": "Backup operation began",
        "publisher": "aria_core.event_bus (helper); backup runners",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"op": "str?"},
        "ordering": "paired with BackupCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "BackupCompleted": {
        "purpose": "Backup operation finished",
        "publisher": "aria_core.event_bus (helper); backup runners",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool"},
        "ordering": "after BackupStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RecoveryStarted": {
        "purpose": "Recovery began",
        "publisher": "aria_core.capability_bus.recover",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {},
        "ordering": "paired with RecoveryCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "RecoveryCompleted": {
        "purpose": "Recovery finished",
        "publisher": "aria_core.capability_bus.recover",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"ok": "bool"},
        "ordering": "after RecoveryStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "StartupPhaseChanged": {
        "purpose": "Startup pipeline phase changed",
        "publisher": "mission_control / startup bridge",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {"phase": "str"},
        "ordering": "startup sequence order",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ShutdownStarted": {
        "purpose": "Shutdown began",
        "publisher": "mission_control / runtime bridge",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {},
        "ordering": "paired with ShutdownCompleted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "ShutdownCompleted": {
        "purpose": "Shutdown finished",
        "publisher": "mission_control / runtime bridge",
        "subscribers": ["timeline", "mission_control.events"],
        "payload": {},
        "ordering": "after ShutdownStarted",
        "reliability": "best-effort in-process",
        "replay_support": "ring buffer only",
        "version": EVENT_VERSION,
    },
    "CognitionStarted": {
        "purpose": "Cognitive Orchestrator began coordinating a Cap Bus request",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.events", "mission_control.cognition"],
        "payload": {"cognition_id": "str", "capability": "str", "selected": "list[str]"},
        "ordering": "paired with CognitionCompleted",
        "reliability": "best-effort; never blocks Cap Bus",
        "replay_support": "cognition history + event ring",
        "version": EVENT_VERSION,
    },
    "CapabilitySelected": {
        "purpose": "An organ was selected to participate",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.cognition"],
        "payload": {"cognition_id": "str", "capability": "str", "organ": "str"},
        "ordering": "after CognitionStarted",
        "reliability": "best-effort in-process",
        "replay_support": "cognition history",
        "version": EVENT_VERSION,
    },
    "CapabilitySkipped": {
        "purpose": "An organ was skipped for this request",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.cognition"],
        "payload": {"cognition_id": "str", "capability": "str", "organ": "str", "reason": "str"},
        "ordering": "after CognitionStarted",
        "reliability": "best-effort in-process",
        "replay_support": "cognition history",
        "version": EVENT_VERSION,
    },
    "PlanningRequested": {
        "purpose": "Planning organ requested by orchestrator",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.cognition"],
        "payload": {"cognition_id": "str", "capability": "str", "organ": "str"},
        "ordering": "before plan organ work",
        "reliability": "best-effort in-process",
        "replay_support": "cognition history",
        "version": EVENT_VERSION,
    },
    "ReasoningRequested": {
        "purpose": "Reasoning organ requested by orchestrator",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.cognition"],
        "payload": {"cognition_id": "str", "capability": "str", "organ": "str"},
        "ordering": "before reason/infer organ work",
        "reliability": "best-effort in-process",
        "replay_support": "cognition history",
        "version": EVENT_VERSION,
    },
    "ReferenceRequested": {
        "purpose": "Reference organ requested by orchestrator",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.cognition"],
        "payload": {"cognition_id": "str", "capability": "str", "organ": "str"},
        "ordering": "before reference organ work",
        "reliability": "best-effort in-process",
        "replay_support": "cognition history",
        "version": EVENT_VERSION,
    },
    "MemoryRequested": {
        "purpose": "Memory organ requested by orchestrator",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.cognition"],
        "payload": {"cognition_id": "str", "capability": "str", "organ": "str"},
        "ordering": "before memory organ work",
        "reliability": "best-effort in-process",
        "replay_support": "cognition history",
        "version": EVENT_VERSION,
    },
    "KnowledgeRequested": {
        "purpose": "Knowledge organ requested by orchestrator",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.cognition"],
        "payload": {"cognition_id": "str", "capability": "str", "organ": "str"},
        "ordering": "before knowledge organ work",
        "reliability": "best-effort in-process",
        "replay_support": "cognition history",
        "version": EVENT_VERSION,
    },
    "LearningRequested": {
        "purpose": "Learning organ requested by orchestrator",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.cognition"],
        "payload": {"cognition_id": "str", "capability": "str", "organ": "str"},
        "ordering": "before learning organ work",
        "reliability": "best-effort in-process",
        "replay_support": "cognition history",
        "version": EVENT_VERSION,
    },
    "CognitionCompleted": {
        "purpose": "Cognitive Orchestrator finished coordinating a request",
        "publisher": "aria_core.cognitive_orchestrator",
        "subscribers": ["timeline", "mission_control.events", "mission_control.cognition"],
        "payload": {
            "cognition_id": "str",
            "capability": "str",
            "ok": "bool",
            "duration_ms": "float",
        },
        "ordering": "after organ work",
        "reliability": "best-effort; never alters Cap Bus result",
        "replay_support": "cognition history + event ring",
        "version": EVENT_VERSION,
    },
    "ReflexMatched": {
        "purpose": "Reflex Layer satisfied a request before cognition",
        "publisher": "aria_core.reflex_engine",
        "subscribers": ["timeline", "mission_control.reflex", "mission_control.events"],
        "payload": {
            "category": "str",
            "pattern_id": "str",
            "action": "str",
            "confidence": "float",
            "duration_ms": "float",
        },
        "ordering": "pre-NLU / pre-Cap-Bus",
        "reliability": "best-effort in-process",
        "replay_support": "reflex history + event ring",
        "version": EVENT_VERSION,
    },
    "ReflexEscalated": {
        "purpose": "Reflex Layer did not match; request continues to cognition path",
        "publisher": "aria_core.reflex_engine",
        "subscribers": ["timeline", "mission_control.reflex"],
        "payload": {"reason": "str", "duration_ms": "float"},
        "ordering": "pre-NLU",
        "reliability": "best-effort in-process",
        "replay_support": "reflex history",
        "version": EVENT_VERSION,
    },
    "ReflexFailed": {
        "purpose": "Reflex Layer evaluation failed; escalate safely",
        "publisher": "aria_core.reflex_engine",
        "subscribers": ["timeline", "mission_control.reflex"],
        "payload": {"error": "str", "duration_ms": "float"},
        "ordering": "pre-NLU",
        "reliability": "best-effort; never blocks escalation",
        "replay_support": "reflex history",
        "version": EVENT_VERSION,
    },
    "ReflexLatency": {
        "purpose": "Reflex Layer latency sample for Mission Control",
        "publisher": "aria_core.reflex_engine",
        "subscribers": ["mission_control.reflex"],
        "payload": {
            "duration_ms": "float",
            "matched": "bool",
            "category": "str?",
            "failed": "bool?",
        },
        "ordering": "with match/escalate/fail",
        "reliability": "best-effort in-process",
        "replay_support": "reflex history",
        "version": EVENT_VERSION,
    },
}


_REQUIRED = (
    "purpose",
    "publisher",
    "subscribers",
    "payload",
    "ordering",
    "reliability",
    "replay_support",
    "version",
)


def get_contract(event_type: str) -> dict[str, Any] | None:
    rec = CONTRACTS.get(event_type)
    return dict(rec) if rec else None


def list_contracts() -> list[dict[str, Any]]:
    return [dict(CONTRACTS[k]) for k in sorted(CONTRACTS)]


def validate_contracts() -> list[str]:
    errors: list[str] = []
    for name in ALL_EVENT_TYPES:
        if name not in CONTRACTS:
            errors.append(f"missing contract: {name}")
    for name, rec in CONTRACTS.items():
        if name not in ALL_EVENT_TYPES:
            errors.append(f"orphan contract: {name}")
        for field in _REQUIRED:
            if field not in rec:
                errors.append(f"{name}: missing {field}")
    return errors
