"""Ownership registry for Aria Core modules (Phase 2).

Every Core module declares exactly one owner. Implementations remain under
jarvis/aiplatform until a later migration phase moves them.
"""

from __future__ import annotations

from typing import Any

OWNERSHIP: dict[str, dict[str, Any]] = {
    "identity": {
        "owner": "aria_core.identity",
        "responsibilities": [
            "Aria identity and operating profiles (standard / uncensored)",
            "Personality / system-prompt selection surface",
        ],
        "public_api": ["profile_name", "is_uncensored", "system_prompt"],
        "private_api": [],
        "dependencies": ["jarvis.config", "jarvis.app_settings"],
        "consumers": ["interfaces", "reasoning", "applications"],
        "allowed_writers": ["aria_core.identity", "jarvis.config"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.config / jarvis.app_settings",
        "implementation": "jarvis.config",
        "future_owner": "aria_core.identity",
    },
    "memory": {
        "owner": "aria_core.memory",
        "responsibilities": ["Long-term and working memory access"],
        "public_api": ["MemoryStore", "create_memory_store"],
        "private_api": [],
        "dependencies": ["jarvis.modules.memory", "jarvis.learning_governor"],
        "consumers": ["applications", "reasoning", "interfaces"],
        "allowed_writers": ["aria_core.memory", "aria_core.learning", "jarvis.modules.memory*"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis memory stores (legacy authoritative until cutover)",
        "implementation": "jarvis.modules.memory",
        "future_owner": "aria_core.memory",
    },
    "knowledge": {
        "owner": "aria_core.knowledge",
        "responsibilities": ["Knowledge registry and RAG search surface"],
        "public_api": ["search", "registry"],
        "private_api": [],
        "dependencies": ["jarvis.knowledge"],
        "consumers": ["applications", "reference", "reasoning"],
        "allowed_writers": ["aria_core.knowledge", "jarvis.knowledge"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.knowledge (+ platform dual-write)",
        "implementation": "jarvis.knowledge",
        "future_owner": "aria_core.knowledge",
    },
    "learning": {
        "owner": "aria_core.learning",
        "responsibilities": ["Learning Governor propose/commit surface"],
        "public_api": ["propose", "commit", "enabled", "Proposal"],
        "private_api": ["recent_audit"],
        "dependencies": ["jarvis.learning_governor"],
        "consumers": ["memory", "reasoning", "nlu via jarvis"],
        "allowed_writers": ["aria_core.learning", "jarvis.learning_governor"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.learning_governor (passthrough Phase 1)",
        "implementation": "jarvis.learning_governor",
        "future_owner": "aria_core.learning",
    },
    "reasoning": {
        "owner": "aria_core.reasoning",
        "responsibilities": ["Conversation / LLM orchestration surface"],
        "public_api": ["get_assistant", "chat"],
        "private_api": [],
        "dependencies": ["jarvis.assistant", "jarvis.llm"],
        "consumers": ["interfaces", "applications"],
        "allowed_writers": ["aria_core.reasoning", "jarvis.assistant"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.assistant / jarvis.llm",
        "implementation": "jarvis.assistant",
        "future_owner": "aria_core.reasoning",
    },
    "planning": {
        "owner": "aria_core.planning",
        "responsibilities": ["Planner and multi-agent coordination surface"],
        "public_api": ["coordinator_available", "planner_store_path"],
        "private_api": [],
        "dependencies": ["jarvis.agents", "jarvis.planner_store"],
        "consumers": ["applications", "capabilities"],
        "allowed_writers": ["aria_core.planning", "jarvis.agents", "jarvis.planner_store"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.agents / jarvis.planner_store",
        "implementation": "jarvis.agents.coordinator",
        "future_owner": "aria_core.planning",
    },
    "reference": {
        "owner": "aria_core.reference",
        "responsibilities": ["Local-first reference / docs search"],
        "public_api": ["search_reference"],
        "private_api": [],
        "dependencies": ["jarvis.reference_engine"],
        "consumers": ["reasoning", "interfaces", "operations"],
        "allowed_writers": ["aria_core.reference"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.reference_engine",
        "implementation": "jarvis.reference_engine",
        "future_owner": "aria_core.reference",
    },
    "runtime": {
        "owner": "aria_core.runtime",
        "responsibilities": ["RuntimeClient / Mission Control connection surface"],
        "public_api": ["RuntimeClient", "execution_mode"],
        "private_api": [],
        "dependencies": ["jarvis.runtime_client", "jarvis.runtime_introspection"],
        "consumers": ["interfaces", "operations", "platform"],
        "allowed_writers": ["aria_core.runtime"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.runtime_client",
        "implementation": "jarvis.runtime_client",
        "future_owner": "aria_core.runtime",
    },
    "capabilities": {
        "owner": "aria_core.capabilities",
        "responsibilities": [
            "Capability Bus verbs",
            "Capability Registry + Contracts",
            "Behavioral contract catalog pointers",
        ],
        "public_api": [
            "list_capability_ids",
            "describe",
            "list_bus_verbs",
            "capability_interface",
            "mission_control_panel",
            "remember",
            "recall",
            "learn",
            "reason",
            "plan",
            "reference",
            "search",
            "infer",
            "execute_tool",
            "schedule",
            "observe",
            "notify",
            "diagnose",
            "repair",
            "backup",
            "recover",
        ],
        "private_api": ["validate_registry", "validate_contracts"],
        "dependencies": [
            "aria_core.capability_bus",
            "aria_core.capability_registry",
            "aria_core.memory",
            "aria_core.learning",
            "jarvis.handlers",
        ],
        "consumers": ["applications", "interfaces", "operations"],
        "allowed_writers": ["aria_core.capabilities"],
        "allowed_readers": ["*"],
        "source_of_truth": "aria_core.capability_registry + BEHAVIORAL_CONTRACT.json",
        "implementation": "delegates to jarvis/aiplatform organs (unchanged)",
        "future_owner": "aria_core.capabilities",
    },
    "interfaces": {
        "owner": "aria_core.interfaces",
        "responsibilities": ["Interface entrypoint pointers (GUI/CLI/API/MC)"],
        "public_api": ["describe_interfaces"],
        "private_api": [],
        "dependencies": ["jarvis.gui", "jarvis.daemon", "aiplatform.mission_control"],
        "consumers": ["humans", "automation"],
        "allowed_writers": ["aria_core.interfaces"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.gui / aiplatform.mission_control",
        "implementation": "jarvis.gui.server / aiplatform.mission_control",
        "future_owner": "aria_core.interfaces",
    },
    "applications": {
        "owner": "aria_core.applications",
        "responsibilities": ["ApplicationHost / manifest attachment surface"],
        "public_api": ["get_host_module", "application_ids"],
        "private_api": [],
        "dependencies": ["jarvis.application.host", "aiplatform.applications"],
        "consumers": ["platform", "runtime"],
        "allowed_writers": ["aria_core.applications"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.application.host + aiplatform.applications",
        "implementation": "jarvis.application.host",
        "future_owner": "aria_core.applications",
    },
    "platform": {
        "owner": "aria_core.platform",
        "responsibilities": ["Workstation lifecycle / platform CLI surface"],
        "public_api": ["workstation_available", "platform_root_hint"],
        "private_api": [],
        "dependencies": ["aiplatform.workstation", "jarvis.workstation"],
        "consumers": ["operations", "interfaces"],
        "allowed_writers": ["aria_core.platform"],
        "allowed_readers": ["*"],
        "source_of_truth": "aiplatform.workstation (when present)",
        "implementation": "aiplatform.workstation / jarvis.workstation shim",
        "future_owner": "aria_core.platform",
    },
    "services": {
        "owner": "aria_core.services",
        "responsibilities": ["Managed service lifecycle surface"],
        "public_api": ["list_managed_services"],
        "private_api": [],
        "dependencies": ["jarvis.services"],
        "consumers": ["runtime", "infrastructure"],
        "allowed_writers": ["aria_core.services", "jarvis.services"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.services",
        "implementation": "jarvis.services",
        "future_owner": "aria_core.services",
    },
    "operations": {
        "owner": "aria_core.operations",
        "responsibilities": ["Mission Control / ops cockpit surface"],
        "public_api": ["mission_control_available", "collect_overview"],
        "private_api": [],
        "dependencies": ["aiplatform.mission_control", "jarvis.mission_control"],
        "consumers": ["interfaces"],
        "allowed_writers": ["aria_core.operations"],
        "allowed_readers": ["*"],
        "source_of_truth": "aiplatform.mission_control",
        "implementation": "aiplatform.mission_control.aggregator",
        "future_owner": "aria_core.operations",
    },
    "infrastructure": {
        "owner": "aria_core.infrastructure",
        "responsibilities": ["GPU/VRAM and infra pointers"],
        "public_api": ["vram_guard_available"],
        "private_api": [],
        "dependencies": ["jarvis.vram_guard", "jarvis.gpu"],
        "consumers": ["services", "capabilities"],
        "allowed_writers": ["aria_core.infrastructure"],
        "allowed_readers": ["*"],
        "source_of_truth": "jarvis.vram_guard / jarvis.gpu",
        "implementation": "jarvis.vram_guard",
        "future_owner": "aria_core.infrastructure",
    },
}


def module_ownership(name: str) -> dict[str, Any]:
    """Return ownership record for a Core module name."""
    try:
        return dict(OWNERSHIP[name])
    except KeyError as exc:
        raise KeyError(f"Unknown Aria Core module: {name}") from exc


def all_module_names() -> list[str]:
    return sorted(OWNERSHIP.keys())
